### ISSUE TITLE
[bug] when there are no services currently starting, it will continuously display "services loading..."

### ISSUE THREAD

**Issue by zooobb** [persiliao/brew-services-manage#1]
### Describe the bug

this is an optimization suggestion.
when there are no services currently starting, it will continuously display "services loading..."
![image](https://github.com/user-attachments/assets/da1c0f37-bd00-4d78-b2a2-da8b6c69966c)

### Full System information output

```text
none
```

**Comment by persiliao** [comment]
Because there is no service installed, the list will be loaded regardless of whether it is started or not.

**Comment by persiliao** [comment]
@zooobb Version 1.0.1 has been fixed
